In [1]:
import sys
import pandas as pd 
import numpy as np
# path to where package is located (change accordingly)
pack_path = '/home/massimiliano/work_vivo/pioggia/disdrorain'

if pack_path not in sys.path:
    sys.path.append(pack_path)

import disdrorain as dr
import disdrorain_wspeed as drsp

In [2]:
# reload modules
%load_ext autoreload
%autoreload 2
%aimport disdrorain
%aimport disdrorain_wspeed

In [4]:
disdrodata_path='/home/massimiliano/work_vivo/pioggia/bulkvar_approx_analysis/disdrometer'
disdrocell_RD69='/home/massimiliano/work_vivo/pioggia/bulkvar_approx_analysis/disdrometer/celllimits_RD69_20cl_darwin_row_noheader'

In [9]:
_DRW_=dr.disdrorain(classpath=disdrocell_RD69,datapath=disdrodata_path+'/DRW')
(_DRW_noout,_DRW_summary) = _DRW_.outlier_deletion()

/home/massimiliano/work_vivo/virtualenv/standard/lib/python3.6/site-packages/pandas/core/frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [11]:
_DRW_noout.data.head(5)

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20
record number,,,,,,,,,,,,,,,,,,,,
0,5,7,8,13,13,18,18,3,0,0,0,0,0,0,0,0,0,0,0,0
1,0,4,3,64,47,130,235,143,103,107,183,177,80,64,61,23,28,9,4,4
2,0,0,0,3,8,46,195,150,110,166,315,248,116,86,55,32,10,3,4,0
3,0,0,24,90,127,294,523,365,236,270,357,245,95,58,32,11,5,0,0,0
4,0,0,16,46,80,278,468,286,219,179,317,222,113,95,68,25,16,5,0,0